### PR TITLE
chore: extract base protocol

### PR DESCRIPTION
**Pull request by vasco-santos**
Refactor to use  `libp2p-pubsub` base protocol extracted from this module.

### CODE REVIEW

**Comment by vasco-santos** [comment]
Ups, that's right. I forgot to consider those.

So, those could be overridden if their implementation uses the extended class implementation. We may need both functions to do additional logic. I will add this to `libp2p-pubsub` docs!

**Comment by jacobheun** [comment]
We should note whether or not `super()` needs to be called for each of those, and if you don't call `super` what you'd need to implement.

**Comment by vasco-santos** [comment]
yes, I will look at it better next week. Hopefully gossipsub implementation will also allow us to improve the docs, as floodsub was implemented first than the base protocol

**Comment by vasco-santos** [comment]
@jacobheun docs updated [libp2p/js-libp2p-pubsub#6](https://github.com/libp2p/js-libp2p-pubsub/pull/6)

**Pull request merged**
