### PR TITLE
feat: match expectation on start (that dials are done)

### PR DESCRIPTION
**Pull request by diasdavid**

### CODE REVIEW

**Comment by diasdavid** [comment]
Looking for a humble 👍  <3

**Comment by RichardLitt** [comment]
@diasdavid Working on it. Would be better if there was a test with this PR.

**Comment by diasdavid** [comment]
@RichardLitt a test for you, my kind sir 👑 thank you! :)

**Comment by RichardLitt** [comment]
This looks fine to me. Tests pass, and I think the code is pretty clear.

**Pull request merged**
